### ISSUE TITLE
Solax API from my equipment with new Firmware 

### ISSUE THREAD

**Issue by Bl00d-B0b** [nazar-pc/solax-local-api-docs#9]
Hello,

this is an API from my SolaX EV Charger
X3-EVC-11K(PHX) API:
{"SN":"SQxxxxxxxx","ver":"3.004.11","type":1,"Data":[4,0,24162,24336,24694,0,0,0,0,0,0,0,0,0,0,0,37,65503,32,0,65534,0,0,0,32,0,0,15,1,0,0,0,0,4996,4996,4992,8753,7947,6149,5,0,0,0,0,0,0,0,0,1,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4895,7168,6149,0,1,1,1,0,0,121,1195,1000,64936,44,0,0,0,1,0],"Information":[11.000,1,"C3xxxxxxxxxxxx",1,1.13,1.01,0.00,0.00,0.00,1],"Error":{"ErrorCode":"0","ErrorData":[0.00,0,0.00,0.0,0.00,0,0.00,0.00,0.00,0.00,0.00,86.43,0.00]},"OCPPServer":"","OCPPChargerId":""}

{"SN":"SQxxxxxxxx","ver":"3.008.02","type":1,"Data":[4,0,24037,24583,24528,0,0,0,0,0,0,0,0,0,1,0,37,65502,65503,1,65532,65535,0,0,30,0,0,15,1,0,0,0,0,4998,4996,4996,7207,782,6150,1,0,0,0,0,0,0,0,0,1,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4895,7168,6149,0,1,1,1,0,0,121,1195,1000,0,44,0,0,0,1,0],"Information":[11.000,1,"C3xxxxxxxxxxxx",1,1.13,1.01,0.00,0.00,0.00,1],"Error":{"ErrorCode":"0","ErrorData":[0.00,0,0.00,0.0,0.00,0,0.00,0.00,0.00,0.00,0.00,86.43,0.00]},"OCPPServer":"","OCPPChargerId":"","QRContent":""}

X3-MIC-8K G2 API:
{"sn":"SRxxxxxxxx","ver":"3.016.02","type":16,"Data":[2456,2396,2455,81,82,83,2071,2049,2057,4313,4287,0,74,74,0,3199,3208,0,4999,4999,4999,2,30069,0,205,8000,53,43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6179,0,2,5,7,0,15978,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"Information":[8.000,16,"MCxxxxxxxxxxxx",8,1.27,0.00,1.29,1.00,0.00,1]}

**Comment by nazar-pc** [comment]
Thanks, what do you want me to do with it though?

The documentation produced is based on the source code of the Android app, not on acual samples (though it is definitely helpful to have responses published somewhere).

**Comment by Bl00d-B0b** [comment]
Jus in case its helps

**Comment by nazar-pc** [comment]
I see. I'll close issue then, but people would be able to find it afterwards through search :+1:
